##====---- fwkSudoku Codecov configuration                            ----====##
# Repository yaml.
# Documentation: https://docs.codecov.io
##====--------------------------------------------------------------------====##
coverage:
  precision: 5
  round: down
  range: "85...100"

  status:
    project:
      default: true # entire project
      sudoku:
        paths:
        - "Sudoku/Sudoku/"
        base: auto
        target: auto
        threshold: 0.5%
      tests:
        paths:
        - "SudokuTests/"
        base: auto
        target: 0
    patch: true
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

# Pull-request Comments
comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
