##====---- fwkSudoku Codecov configuration                            ----====##
# Repository yaml.
# Documentation: https://docs.codecov.io
##====--------------------------------------------------------------------====##
coverage:
  precision: 5
  round: down
  range: "85...100"

  status:
    project:
      default: yes # entire project
      sudoku:
        paths:
        - "Sudoku/Sudoku/"
        base: auto
        target: auto
        threshold: 0.5%
      tests:
        paths:
        - "SudokuTests/"
        base: auto
        target: 0
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# Pull-request Comments
comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no
