##====---- .travis.yml                                                ----====##
# TravisCI build configuration.
# Continuous integration testing on Linux and OSX. Using GCC, LLVM/Clang and
# AppleClang. Debug and Release builds, unit tests and codecoverage.
language: cpp

git:
  depth: 20
  quiet: true

env:
  global:
  # vcpkg
  - TOOLCHAIN_FILE: "$HOME/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"

##====--------------------------------------------------------------------====##
## Define Build Configurations
# No build matrix, each item in matrix:include is single build configuration.
#
# Environment variables:
# - C_compiler: overwrites default value of CC.
# - CXX_compiler: overwrites default value of CXX.
# - CXX_lib: library selection.
#   - libc++  (Linux only, default on OSX.)
# - CONFIGURATION: specifies the build configuration.
#   When not set both a Debug and a Release configurations are build in single
#   job session.
# - Coverage:
#   Send code coverage data to codecov.io.
#   When no CONFIGURATION defined, only Debug build runs coverage.
#   - grcov: currently the only option supporting LLVM/clang and AppleClang.
#   - lcov:  GNU tool, mostly redundant by Codecov's bash script.
#   - *: if an executable on the PATH, like: gcov-6, run by the bash script.
#   - any other value runs the bash script in default mode. (I.e. true)
#
## Toolchain installation information:
# https://docs.travis-ci.com/user/installing-dependencies/
# Finding apt packages:
# https://packages.ubuntu.com/search
# Ubuntu Toolchain test builds:
# https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
# LLVM apt resources:
# https://apt.llvm.org
# TravisCI apt safelist:
# https://github.com/travis-ci/apt-source-safelist/blob/master/ubuntu.json
# libc++ documentation:
# https://libcxx.llvm.org/docs/UsingLibcxx.html
# Homebrew OSX packages:
# https://formulae.brew.sh/formula/

# Defaults
os: linux
dist: xenial

# Specify Stage Order and Conditions
stages:
- "Build & Test Latest" # First: (4) builds to run first 
- name: "Build & Test"  # If all succeed build rest
  if: NOT (branch =~ /^[Aa]pp[Vv]eyor.*/)

jobs:
  include:
  - name: GCC-8
    stage: "Build & Test Latest"
    env:
    - C_compiler:   gcc-8
    - CXX_compiler: g++-8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8

  - name: GCC-7
    stage: "Build & Test Latest"
    env:
    - C_compiler:   gcc-7
    - CXX_compiler: g++-7
    - Coverage:     gcov-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7

  - name: Clang-8
    stage: "Build & Test Latest"
    dist: xenial
    env:
    - C_compiler:   clang-8
    - CXX_compiler: clang++-8
    - Coverage: grcov
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-8
        - ubuntu-toolchain-r-test
        packages:
        - clang-8
        - g++-7

  - name: Clang-8 libc++
    stage: "Build & Test Latest"
    dist: xenial
    env:
    - C_compiler:   clang-8
    - CXX_compiler: clang++-8
    - CXX_lib: libc++
    - Coverage: grcov
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-8
        - ubuntu-toolchain-r-test
        packages:
        - clang-8
        - g++-7
        - libc++-8-dev
        - libc++abi-8-dev

  - name: Clang-7
    stage: "Build & Test"
    dist: xenial # Ships with Clang 7
    env:
    - C_compiler:   clang
    - CXX_compiler: clang++
    - Coverage: grcov
    addons:
      apt: # vcpkg executable requires GCC 7 or better
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7

  - name: Clang-7 libc++
    dist: xenial
    env:
    - C_compiler:   clang
    - CXX_compiler: clang++
    - CXX_lib: libc++
    - Coverage: grcov
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-7
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - libc++-7-dev
        - libc++abi-7-dev

  - name: Clang-6.0
    dist: xenial
    env:
    - C_compiler: clang-6.0
    - CXX_compiler: clang++-6.0
    - Coverage: grcov
    addons:
      apt:
        sources:
        - llvm-toolchain-xenial-6.0
        - ubuntu-toolchain-r-test
        packages:
        - clang-6.0
        - g++-7

  - name: Clang-5.0
    dist: xenial
    env:
    - C_compiler: clang-5.0
    - CXX_compiler: clang++-5.0
    - Coverage: grcov
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - clang-5.0
        - g++-7

  - name: Clang-4.0 Debug
    if: branch =~ /^[Tt]ravis.*$/
    dist: xenial
    env:
    - C_compiler: clang-4.0
    - CXX_compiler: clang++-4.0
    - CONFIGURATION: Debug
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - clang-4.0
        - g++-7

  - name: AppleClang Xcode-10.2
    os: osx
    osx_image: xcode10.2 # AppleClang 10.0.1
    env:
    - Coverage: grcov
    addons:
      homebrew:
        packages:
        - ninja
        - gcc@7 # vcpkg requires gcc-7 or later

  - name: AppleClang Xcode-10.1
    if: branch =~ /^(master|[Tt]ravis.*)$/
    os: osx
    osx_image: xcode10.1 # AppleClang 10.0.0 same compiler as Xcode 10.0
    env:
    - Coverage: grcov
    addons:
      homebrew:
        packages:
        - ninja
        - gcc@7 # vcpkg requires gcc-7 or better

  - name: AppleClang Xcode-9.4
    if: branch =~ /^[Tt]ravis.*$/
    os: osx
    osx_image: xcode9.4 # AppleClang 9.1.0 same compiler as Xcode 9.3
    env:
    - Coverage: grcov
    addons: &OSX-legacy
      homebrew:
        packages:
        - ninja
        - gcc@7 # vcpkg requires gcc-7 or better
        - cmake # Xcode 9.4 and earlier have 3.11.4
        update: true

  - name: AppleClang Xcode-9
    if: branch =~ /^(master|[Tt]ravis.*)$/
    os: osx
    osx_image: xcode9 # AppleClang 9.1.0 same compiler in Xcode 9.0, 9.1 and 9.2
    env:
    - Coverage: grcov
    addons: *OSX-legacy

  allow_failures:
  - name: Clang-4.0 Debug
  - name: AppleClang Xcode-9.4

##====--------------------------------------------------------------------====##
## Install tools and dependencies
before_install:
- |
  # Setup
  mkdir -p ~/tools && cd ~/tools
  if [[ ${C_compiler:-} ]]; then   export CC=${C_compiler:?}; fi
  if [[ ${CXX_compiler:-} ]]; then export CXX=${CXX_compiler:?}; fi
  if [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
    export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
  fi
- |
  # Install Ninja-build (if not installed)
  if [[ ! -x "$(command -v ninja)" ]]; then
  ( set -euxo pipefail
    NINJA_VER="v1.9.0"
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      file_name="ninja-linux.zip"
      NINJA_SHA512="751fd86520a1a38fb47baadf4a46ab49f9ebb11d6ff9c01e71326564ebf10f141ca2627620e315fcab82db1493a30123f11194f41226241d80413d5008acfc59"
    elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
      file_name="ninja-mac.zip"
      NINJA_SHA512="ec2294b430b89134f54f3388bafd760697c7eb33792bc094416b918371619e79592629973a60fcc35335a92eaa9ed84a41f2bc53c846eb8abf3422d4322cd3e5"
    fi
    echo "-- Install Ninja-build..."
    NINJA_URL="https://github.com/ninja-build/ninja/releases/download/${NINJA_VER}/${file_name}"
    wget -q "${NINJA_URL}" --tries=3 --timeout 90 -nc
    sum=$(sha512sum ${file_name})
    if [[ ${sum:0:128} = ${NINJA_SHA512} ]]; then
      unzip -q ${file_name} -d ninja
      chmod -c +x ninja/ninja
      echo "-- Install Ninja-build... done"
    else
      echo "Ninja hash has changed!"  >&2
      echo "Expecting: $NINJA_SHA512" >&2
      echo "Actual:    $sum"          >&2
      exit 1
    fi
  )
  export PATH=$HOME/tools/ninja:$PATH
  fi
- |
  # Install Mozilla/grcov
  if [[ ${Coverage:-} && ${Coverage} == "grcov" ]]; then
  ( set -euxo pipefail
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      GRCOV_TAG="v0.5.1"
      GRCOV_SHA512="5086b0b53ba15843ca83c55e4ea95cdccf544fd648382cab8d603e9f634772f4edf7221032809f35055986c29c7fa6678ab2ab291e4f9c430f3068117239996e"
    elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
      GRCOV_TAG="v0.5.1"
      GRCOV_SHA512="26ffcea469e3e02b55352766c2a8889f34c116e03acc809abf22a78b027173a7e3c6c34144ba98338f3c10d231139b878b1f70517cb2a39084d1a0227222de6a"
    fi
    echo "-- Install grcov..."
    file_name="grcov-${TRAVIS_OS_NAME}-x86_64.tar.bz2"
    GRCOV_URL="https://github.com/mozilla/grcov/releases/download/${GRCOV_TAG}/${file_name}"
    wget "${GRCOV_URL}" --tries=3 --timeout 90 -nc
    sum=$(sha512sum ${file_name})
    sum=${sum:0:128}
    if [[ ${sum} == ${GRCOV_SHA512} ]]; then
      mkdir -p ~/tools/grcov
      tar --extract --bzip2 --file=${file_name} --directory=grcov
      chmod -c +x grcov/grcov
      rm ${file_name}
      echo "-- Install grcov... done"
    else
      echo "grcov hash has changed!"    >&2
      echo "Expecting: ${GRCOV_SHA512}" >&2
      echo "Actual:    ${sum}"          >&2
      exit 1
    fi
  )
  export PATH=$HOME/tools/grcov:$PATH
  fi
- |
  # Download vcpkg
  ( set -euo pipefail
    git clone --depth=1 --branch=master --quiet \
      https://github.com/Microsoft/vcpkg.git $HOME/tools/vcpkg
    mv -f -t ~/tools/vcpkg ~/tools/.cache/vcpkg/* ||
      echo "No cached files for vcpkg."
  )
  export PATH=$PATH:$HOME/tools/vcpkg
- |
  # Install/Update vcpkg
  ( set -euxo pipefail
    if [[ ! -x "$(command -v vcpkg)" ||
      ( $(vcpkg update) == 'Warning: Different source'*'for vcpkg' ) ]]
    then
      if [[ ${TRAVIS_OS_NAME} == "linux" &&
        ( ${CXX_compiler} != g++* || ${CXX_compiler%g++-} < 7 ) ]]
      then
        eval "CC=gcc-7 && CXX=g++-7" # Minimum requirement vcpkg on Linux
      elif [[ ${TRAVIS_OS_NAME} == "osx" ]]; then
        eval "CC=gcc-7 && CXX=g++-7" # Minimum requirement vcpkg on OSX
      fi
      ~/tools/vcpkg/bootstrap-vcpkg.sh
    fi
  )
- |
  # Using libc++
  if [[ ${CXX_compiler} == clang* && ${CXX_lib:-} ]]; then
    FLAGS="-stdlib=${CXX_lib}"
    #if [[ ${CXX_lib} == libc++ ]]; then
    #  FLAGS="${FLAGS} -lc++fs"
    #  FLAGS="${FLAGS} -lc++experimental"
    #fi
    export CXXFLAGS="${CXXFLAGS} ${FLAGS}"
  fi

install:
- vcpkg install ms-gsl
- vcpkg install gtest
- |
  # Update installed packages
  ( set -euo pipefail
    vcpkg update # print potential updates
    if [[ $(vcpkg upgrade) != *'installed packages are up-to-date'* ]]
    then
      vcpkg upgrade --no-dry-run
    fi
  )

##====--------------------------------------------------------------------====##
before_script:
- |
  # Configuration
  cd "${TRAVIS_BUILD_DIR}"
  mkdir -p build
  mkdir -p build2
  GeneratorFlags='-k 10' # Ninja
  if [[ ${Coverage} ]]; then coverage_bool="ON"
  else coverage_bool="OFF"
  fi
  export CFLAGS="${CFLAGS} -Werror"
  export CXXFLAGS="${CXXFLAGS} -Werror"
- |
  CMakeGenFlags=("-G Ninja")
  CMakeGenFlags+=("-DCMAKE_BUILD_TYPE=${CONFIGURATION:-Debug}")
  CMakeGenFlags+=("-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE:?}")
  CMakeGenFlags+=("-DCODE_COVERAGE=${coverage_bool:?}")
  CMakeGenFlags+=(-Wdev -Werror=dev --warn-uninitialized)
  echo ${CMakeGenFlags[@]}
  if [[ ! ${CONFIGURATION:-} ]]; then
    B_REL="Build both Debug and Release configurations"
    CMakeGenFlags2=("-G Ninja")
    CMakeGenFlags2+=("-DCMAKE_BUILD_TYPE=Release")
    CMakeGenFlags2+=("-DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE:?}")
    CMakeGenFlags2+=(-Wdev -Werror=dev --warn-uninitialized)
  fi

script:
- cd ./build
- cmake ${CMakeGenFlags[@]:?} ..
- cmake --build . --config ${CONFIGURATION:-Debug} -- ${GeneratorFlags}
- ctest -j $(nproc) --output-on-failure
- cd ../build2
- if [[ ${B_REL:-} ]]; then cmake ${CMakeGenFlags2[@]:?} ..; fi
- if [[ ${B_REL:-} ]]; then cmake --build . --config Release -- ${GeneratorFlags}; fi
- if [[ ${B_REL:-} ]]; then ctest -j $(nproc) --output-on-failure; fi

##====--------------------------------------------------------------------====##
before_cache:
- |
  # Select files for caching
  mkdir -p ~/tools/.cache/vcpkg
  mv -u -t ~/tools/.cache/vcpkg ~/tools/vcpkg/vcpkg ~/tools/vcpkg/installed

cache:
  directories:
  - ~/tools/.cache

##====--------------------------------------------------------------------====##
after_success:
- |
  # Code coverage
  cd "${TRAVIS_BUILD_DIR}"
  if [[ ${Coverage:-} ]]; then
  ( set -euxo pipefail
    bash_flags=("-n ${TRAVIS_JOB_NAME/ /_}") # Replace space with '_'
    if [[ ${Coverage} == "grcov" ]]; then
      coverage_report="coverage.json"
      flags=("-t coveralls+" "--token unused" "--commit-sha ${TRAVIS_COMMIT}")
      if [[ ${CXX_compiler:-} == clang* ]]; then flags+=("--llvm"); fi
      flags+=("--branch")
      grcov ./build ${flags[@]} > ${coverage_report}
    elif [[ ${Coverage} == "lcov" ]]; then
      coverage_report="coverage.info"
      lcov --capture --directory ./build --output-file coverage.info
      lcov --remove coverage.info '/usr/*' --output-file coverage.info
      lcov --list coverage.info
    elif [[ -x "$(command -v ${Coverage})" ]]; then
      bash_flags+=("-x ${Coverage}")
    fi
    if [[ ${coverage_report:-} && -f "${coverage_report}" ]]; then
      bash_flags+=("-f ${coverage_report}")
    fi
    bash <(curl -s https://codecov.io/bash) ${bash_flags[@]} ||
      echo "Codecov did not collect coverage reports"
  )
  fi

##====--------------------------------------------------------------------====##
after_script:
- |
  # Binary sizes:
  ls -l "${TRAVIS_BUILD_DIR}/build/Console/console" 2>/dev/null || echo
  ls -l "${TRAVIS_BUILD_DIR}/build/SudokuTests/SudokuTests" 2>/dev/null || echo
  ls -l "${TRAVIS_BUILD_DIR}/build2/Console/console" 2>/dev/null || echo
  ls -l "${TRAVIS_BUILD_DIR}/build2/SudokuTests/SudokuTests" 2>/dev/null || echo
