language: cpp

git:
  depth: 1
  quiet: true

# Defaults
os: linux
dist: xenial

env:
  global:
  - NINJA_VER=v1.8.2
  - NINJA_SHA512='38fcb68e745c1f15b4b50f20069ffe686b1ef5baf93b74958e132ea5d30d155cf6970d6dc1b095aafd421ebd8bcc63acf4f64e305c496266b5182f99b815cca5  ./ninja.zip'
  - TOOLCHAIN_FILE="$HOME/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"

matrix:
  include:
  - name: GCC-7 Debug
    env:
    - C_compiler=gcc-7
    - CXX_compiler=g++-7
    - CONFIGURATION=Debug
    addons: &GCC7
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7

  - name: GCC-7 Release
    env:
    - C_compiler=gcc-7
    - CXX_compiler=g++-7
    - CONFIGURATION=Release
    addons: *GCC7

  - name: GCC-8 Debug
    env:
    - C_compiler=gcc-8
    - CXX_compiler=g++-8
    - CONFIGURATION=Debug
    addons: &GCC8
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8

  - name: GCC-8 Release
    env:
    - C_compiler=gcc-8
    - CXX_compiler=g++-8
    - CONFIGURATION=Release
    addons: *GCC8

  - name: Clang-6.0 Debug
    dist: xenial
    env:
    - C_compiler=clang-6.0
    - CXX_compiler=clang++-6.0
    - CONFIGURATION=Debug
    addons: &clang6
      apt:
        sources:
        - llvm-toolchain-xenial-6.0
        - ubuntu-toolchain-r-test
        packages:
        - clang-6.0
        - g++-7

  - name: Clang-6.0 Release
    dist: xenial
    env:
    - C_compiler=clang-6.0
    - CXX_compiler=clang++-6.0
    - CONFIGURATION=Release
    addons: *clang6

  - name: Clang-7 Debug
    dist: xenial
    env:
    - C_compiler=clang
    - CXX_compiler=clang++
    - CONFIGURATION=Debug
    addons: &clang7
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7

  - name: Clang-7 Release
    dist: xenial
    env:
    - C_compiler=clang
    - CXX_compiler=clang++
    - CONFIGURATION=Release
    addons: *clang7


before_install:
- mkdir -p ~/tools && cd ~/tools
- |
  eval "CC=${C_compiler:?} && CXX=${CXX_compiler:?}"
- |
  { # Download Ninja-build
    os=${TRAVIS_OS_NAME}
    NINJA_URL="https://github.com/ninja-build/ninja/releases/download/${NINJA_VER}/ninja-${os}.zip"
    wget -q "${NINJA_URL}" --tries=3 -nc -O ninja.zip
  }
- |
  { # Install Ninja-build
    sum=$(sha512sum ./ninja.zip)
    if [[ $sum = ${NINJA_SHA512} ]]; then
      unzip -q ninja.zip -d ninja
      export PATH=$PATH:$PWD/ninja/
    else
      echo "Ninja hash has changed!"  >&2
      echo "Expecting: $NINJA_SHA512" >&2
      echo "Actual:    $sum"          >&2
      exit 1
    fi
  }
- |
  { # Install vcpkg
    if [[ -x ./vcpkg/vcpkg ]]; then
      cd ./vcpkg
      git pull --quiet
    else
      git clone --depth=1 --branch=master --quiet https://github.com/Microsoft/vcpkg.git
      if [[ ${TRAVIS_OS_NAME} == linux && ${CXX_compiler} != g++* || ${CXX_compiler%g++-} < 7 ]]
      then
        eval "CC=gcc-7 && CXX=g++-7"
      fi
      ./vcpkg/bootstrap-vcpkg.sh
    fi
  }

install:
# dependencies
- cd ~/tools/vcpkg
- ./vcpkg install ms-gsl
- ./vcpkg install gtest

before_script:
- |
  { # Configuration
    cd "${TRAVIS_BUILD_DIR}"
    CMakeGenFlags="-G Ninja -DCMAKE_TOOLCHAIN_FILE=${TOOLCHAIN_FILE:?}"
    GeneratorFlags='-k 10' # Ninja
    CMakeBuildFlags="--config ${CONFIGURATION:?} -- ${GeneratorFlags}"
    mkdir -p build
    cd build
  }
- echo $CMakeGenFlags
- cmake .. ${CMakeGenFlags:?}
- echo $CMakeBuildFlags

script:
- cmake --build . ${CMakeBuildFlags:?}

before_cache:
- |
  # Cleaning build cache
  rm -rf ~/tools/vcpkg/buildtrees
  rm -rf ~/tools/vcpkg/downloads

cache:
  directories:
  - ~/tools/vcpkg

after_script: true
