##====---- appveyor.yml                                               ----====##
version: "{build}"
# fetch repository as a zip archive
shallow_clone: true

cache:
- C:\Tools\vcpkg\installed

##====--------------------------------------------------------------------====##
## Build Matrix Configuration
# Dimensions: 4 (image; platform; configuration; environment:matrix)
#
##====-----------------
# Options:              Values (supported for this script):
# ------------------------------------------------------------------------------
# image                 Visual Studio 2017 (default), Visual Studio 2015
# platform              Platform configuration names:
#                       x64 (default), x86
# configuration         Solution configuration names:
#                       Debug, Release ...       (use the MSVC compiler)
#                       LLVM_(Debug, Release)... (use the LLVM/clang compiler)
# USE_MSBUILD_SOLUTION  true - use MSBuild project files
#                       [undefined] - use CMake (default)
# USE_BUILDSYSTEM       MSBuild - (default)
#                       Ninja - requires CMake generator
##====-----------------
## Create_Matrix
image: Visual Studio 2017

platform:
- x86
- x64

configuration:
- Debug
- Release
- LLVM_Debug
- LLVM_Release

environment:
  matrix:
  - USE_BUILDSYSTEM: Ninja
  - USE_BUILDSYSTEM: MSBuild
  - USE_MSBUILD_SOLUTION: true
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    VCVAR2015: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    VCVAR2017: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
    # vcpkg
    TOOLCHAIN_FILE: 'C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake'
## /Create_Matrix
##====-----------------
## Remove_from_Matrix
matrix:
  exclude:
  # Not supported by script / invalid combination:
  - image: Visual Studio 2015
    configuration: LLVM_Debug
    USE_BUILDSYSTEM: MSBuild
  - image: Visual Studio 2015
    configuration: LLVM_Release
    USE_BUILDSYSTEM: MSBuild
  - image: Visual Studio 2015
    USE_MSBUILD_SOLUTION: true
  # Disabled to reduce AppVeyor test-load
  - USE_BUILDSYSTEM: MSBuild
## /Remove_from_Matrix
##====-----------------
## Modify_Matrix
  allow_failures:
  # CMake -> MSBuild Failing error suppression:
  - configuration: Debug
    USE_BUILDSYSTEM: MSBuild
  - configuration: Release
    USE_BUILDSYSTEM: MSBuild
# Specializing matrix job configuration
# Note: overwrites existing, only new variables and notifications are merged.
for:
-
  matrix:
    only:
    - USE_BUILDSYSTEM: Ninja
  environment:
    NINJA_TAG:    v1.8.2
    NINJA_SHA512: 9B9CE248240665FCD6404B989F3B3C27ED9682838225E6DC9B67B551774F251E4FF8A207504F941E7C811E7A8BE1945E7BCB94472A335EF15E23A0200A32E6D5
    NINJA_PATH:   C:\Tools\ninja\ninja-%NINJA_TAG%
  cache:
  - C:\Tools\ninja
  - C:\Tools\vcpkg\installed
-
  matrix:
    only:
    - USE_MSBUILD_SOLUTION: true
  before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  build_script:
  - >-
    MSBuild
    -nologo
    -verbosity:minimal
    -p:Configuration="%CONFIGURATION%"
    -p:Platform="%PLATFORM%"
    -logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  test_script:
  - ps: |
      $env:TEST_EXE_PATH = "$pwd\$env:CONFIGURATION\SudokuTests.exe"
      if (![IO.File]::Exists("$env:TEST_EXE_PATH")) {
        $env:TEST_EXE_PATH = "$pwd\x64\$env:CONFIGURATION\SudokuTests.exe"
        if (![IO.File]::Exists("$env:TEST_EXE_PATH")) {
          Write-Error "Invalid test executable path."
        }
      }
  - >-
    VSTest.Console
    %TEST_EXE_PATH%
    /UseVsixExtensions:true
    /Settings:msvc\GoogleTestAdapter.RunSettings
    /logger:Appveyor
## /Modify_Matrix

##====--------------------------------------------------------------------====##
## Install tools and dependencies
install:
- ps: |
    $out =  "-- CI Session Configuration --`n"
    $out += "$env:APPVEYOR_BUILD_WORKER_IMAGE - $env:CONFIGURATION - "
    $out += "$env:PLATFORM`nOS / platform:       "
    $tmp = (Get-WmiObject Win32_OperatingSystem).name
    $out += "$($tmp -split "[|]" | Select-Object -First 1) / "
    $out += "$((Get-WmiObject Win32_OperatingSystem).OSArchitecture)`n"
    if ($env:USE_MSBUILD_SOLUTION) {
      $out += 'Build configuration: MSBuild projects'
    } else {
      $out += 'Build configuration: CMake // '
      $out += "$(cmake --version | Select-Object -First 1)`n"
      $out += "Build system:        $env:USE_BUILDSYSTEM"
      if ($env:NINJA_TAG) { $out +=": $env:NINJA_TAG" }
    }; Write-Output "$out"
- ps: |
    if("$env:USE_BUILDSYSTEM" -eq "Ninja") {
      Write-Verbose "Install Ninja-build $env:NINJA_TAG"
      if (![IO.File]::Exists("$env:NINJA_PATH\ninja.exe")) {
        Start-FileDownload `
          "https://github.com/ninja-build/ninja/releases/download/$env:NINJA_TAG/ninja-win.zip"
        $hash = (Get-FileHash ninja-win.zip -Algorithm SHA512).Hash
        if ($env:NINJA_SHA512 -eq $hash) {
          7z e -y -bso0 ninja-win.zip -o"$env:NINJA_PATH"
        } else {
          Write-Warning "Ninja download hash changed!"; Write-Output "$hash"
          $env:APPVEYOR_CACHE_SKIP_SAVE = true
        }
      }
      if ([IO.File]::Exists("$env:NINJA_PATH\ninja.exe")) {
        $env:PATH = "$env:NINJA_PATH;$env:PATH"
        ninja --version 1>$null # will fail if not available on path
      } else { Write-Warning "Failed to find ninja.exe in expected location." }
    }
- cd C:\Tools\vcpkg & git pull --quiet
- ps: |
    if ($(vcpkg list) -match "2018-11-08|2018-11-26" -or
      !($(vcpkg list) -match "ms-gsl:$env:PLATFORM-windows")
    ) {
      Write-Warning "Temporary patch for ms-gsl."
      Start-FileDownload `
        "https://gist.githubusercontent.com/Farwaykorse/c1901cf149c69085e6b3001fcc561321/raw/71c2fe5a432fac2cac93d4e4687065468e444bdd/vcpkg_ms-gsl.patch"
      git apply vcpkg_ms-gsl.patch
    }
- vcpkg list
- vcpkg update
- ps: |
    if (
      !($(vcpkg upgrade) -match "^All installed packages are up-to-date") -or
      !(($(vcpkg list) -match "^ms-gsl:$env:PLATFORM-windows").count) -or
      !(($(vcpkg list) -match "^gtest:$env:PLATFORM-windows").count)
    ) {
      if ($(vcpkg version) -match "version 0\.0\.113") {
        Write-Warning "Temporary fix updating vcpkg ..."
        .\bootstrap-vcpkg.bat 1>$null
        vcpkg integrate install 1>$null
      }
      vcpkg upgrade --no-dry-run
    }
- vcpkg install ms-gsl:%PLATFORM%-windows
- vcpkg install gtest:%PLATFORM%-windows

##====--------------------------------------------------------------------====##
before_build:
- ps: |
    if ($env:CONFIGURATION -match "^LLVM_.*") {
      $env:USE_TOOLSET = "llvm"
      $env:CONFIGURATION = $env:CONFIGURATION -replace "^LLVM_",""
    }
- ps: |
    if ("$env:USE_BUILDSYSTEM" -eq "Ninja") {
      $GeneratorFlags = '-k 10'
      $Architecture = $env:PLATFORM
      if ("$env:APPVEYOR_BUILD_WORKER_IMAGE" -match "Visual Studio 2015") {
        $env:VCVARSALL = "`"$env:VCVAR2015`" $Architecture"
      } else {
        $env:VCVARSALL = "`"$env:VCVAR2017`" $Architecture"
      }
      $CMakeGenFlags = "-G Ninja"
    } else {
      $GeneratorFlags = '/m /v:minimal'
      if ("$env:APPVEYOR_BUILD_WORKER_IMAGE" -match "Visual Studio 2015") {
        $Generator = 'Visual Studio 14 2015'
      } else {
        $Generator = 'Visual Studio 15 2017'
      }
      if ("$env:PLATFORM" -eq "x86") { $Architecture = "Win32"}
      else { $Architecture = "x64" }
      if ($env:USE_TOOLSET) {
        $CMakeGenFlags = `
          "-G `"$Generator`" -A $Architecture -T $env:USE_TOOLSET"
      } else {
        $CMakeGenFlags = "-G `"$Generator`" -A $Architecture"
      }
    }
    if ("$env:USE_TOOLSET" -eq "llvm") {
      $env:CC  = "clang-cl"
      $env:CXX = "clang-cl"
      $env:CFLAGS   = "$env:CFLAGS -Werror"
      $env:CXXFLAGS = "$env:CXXFLAGS -Werror"
      if ("$env:PLATFORM" -eq "x86") {
        $env:CFLAGS   = "$env:CFLAGS -m32";
        $env:CXXFLAGS = "$env:CXXFLAGS -m32";
      } else {
        $env:CFLAGS   = "$env:CFLAGS -m64";
        $env:CXXFLAGS = "$env:CXXFLAGS -m64";
      }
    } else {
      $env:CFLAGS   = "$env:CFLAGS /WX"
      $env:CXXFLAGS = "$env:CXXFLAGS /WX"
    }
    $env:CMakeGenFlags = "$CMakeGenFlags"            `
      +" -DCMAKE_TOOLCHAIN_FILE=$env:TOOLCHAIN_FILE" `
      +" -Wdev"                                      `
      +" -Werror=dev"                                `
      +" --warn-uninitialized"
    $env:CMakeBuildFlags = "--config $env:CONFIGURATION -- $GeneratorFlags"
- cd %APPVEYOR_BUILD_FOLDER%
- mkdir build
- cd build
- if %USE_BUILDSYSTEM%==Ninja (call %VCVARSALL%)
- echo %CMakeGenFlags%
- cmake .. %CMakeGenFlags%

##====--------------------------------------------------------------------====##
build_script:
- echo %CMakeBuildFlags%
- cmake --build . %CMakeBuildFlags%

after_build:
- ps: |
    Get-ChildItem -Recurse -Include *.exe, *.dll | Select-Object Length, Name

##====--------------------------------------------------------------------====##
test_script:
- >-
  ctest -j %NUMBER_OF_PROCESSORS%
  --test-action test --no-compress-output
  --quiet

##====--------------------------------------------------------------------====##
deploy: off

##====--------------------------------------------------------------------====##
on_finish:
- ps: |
    # Process test results
    if (Test-Path ".\Testing\TAG") {
      $tag_name = "$(Get-Content .\Testing\TAG -TotalCount 1)"
      Copy-Item .\Testing\$tag_name\Test.xml .\Test.xml
      $template = "https://raw.githubusercontent.com/rpavlik/jenkins-ctest-plugin/master/ctest-to-junit.xsl"
      $XSLInputElement = New-Object System.Xml.Xsl.XslCompiledTransform
      $XSLInputElement.Load("$template")
      $XSLInputElement.Transform(
        (Resolve-Path .\Test.xml),
        (Join-Path (Resolve-Path .) "ctest-to-junit-results.xml")
      )
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile(
        "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)",
        (Resolve-Path .\ctest-to-junit-results.xml)
      )
    }

