##====---- GitHub Actions - cpplint                                   ----====##
# Based on github.com/cpplint/GitHub-Action-for-cpplint
#
name: cpplint
on:
  push:
    paths:
    - '**.[CcHh]'
    - '**.[CcHh]\+\+'
    - '**.[Cc][Cc]'
    - '**.[CcHh][Pp][Pp]'
    - '**.[CcHh][Xx][Xx]'
    - '**CPPLINT.cfg'
    - '**/cpplint.yml'
  pull_request:
    paths:
    - '**.[CcHh]'
    - '**.[CcHh]\+\+'
    - '**.[Cc][Cc]'
    - '**.[CcHh][Pp][Pp]'
    - '**.[CcHh][Xx][Xx]'
    - '**CPPLINT.cfg'
    - '**/cpplint.yml'
  schedule: # Verify main branch weakly with latest release
  - cron: 12 9 * * SAT # Run every Saturday at 09:12 UTC
jobs:
  cpplint:
    name: Run cpplint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --verbose=0 --counting=detailed --recursive .
