##====---- GitHub Actions - cpplint                                   ----====##
# Based on github.com/cpplint/GitHub-Action-for-cpplint
#
name: cpplint
on:
  push:
    paths:
    - '**.[CcHh]'
    - '**.[CcHh]\+\+'
    - '**.[Cc][Cc]'
    - '**.[CcHh][Pp][Pp]'
    - '**.[CcHh][Xx][Xx]'
  pull_request:
    branches: '**'
jobs:
  cpplint:
    name: Run cpplint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --verbose=0 --counting=detailed --recursive .
