##====---- .github/workflow/cpplint.yml                               ----====##
# Based on github.com/cpplint/GitHub-Action-for-cpplint
#
name: cpplint
on: [push, pull_request]
jobs:
  cpplint:
    name: Run cpplint
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-python@v1
    - run: pip install cpplint
    - run: cpplint --verbose=0 --counting=detailed --recursive .
