##====---- GitHub Actions - yamllint                                  ----====##
#
name: yamllint
on:
  push:
    paths:
    - '**.yml'
    - '**.yaml'
    - .clang-format
    - .clang-tidy
  pull_request:
    paths:
    - '**.yml'
    - '**.yaml'
    - .clang-format
    - .clang-tidy
  schedule: # Verify main branch weakly with latest release
  - cron: 18 9 * * SAT # Run every Saturday at 09:18 UTC
jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - run: pip install yamllint
    - run: yamllint --strict .
